### PR TITLE
Add `config` option to executor

### PR DESCRIPTION
**Pull request by yunj**
## Problem

Want to be able to support the playwright `config` option.

## Solution

- Add `config` to executor options

### Useful documentation

- [Contributing guidelines](/marksandspencer/nx-plugins/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by yjing001** [comment]
Hi @crhallen and @andreacaldera, thank you very much for creating this plugin. As @crhallen did for `path`, we want to use the playwright `config` option. Could you please review this pull request and give feedback? Thanks a lot!

**Comment by yunj** [comment]
Hi @crhallen and @andreacaldera, thank you very much for creating this plugin. As @crhallen did for `path` recently, we want to use the playwright `config` option. Could you please review this pull request and give feedback? Thanks a lot!

**Review by andreacaldera — COMMENTED** [review]
Thanks for submitting this @yunj , it looks good to me.
Would you mind bumping up versions again please?

**Comment by yunj** [comment]
> Thanks for submitting this @yunj , it looks good to me. Would you mind bumping up versions again please?

Hi @andreacaldera, thank you very much for the review. The version is bumped up again.

**Review by andreacaldera — APPROVED** [review]

**Pull request merged**
