### PR TITLE
Add additional parameters

### PR DESCRIPTION
**Pull request by ludicast**
## Problem

Needs timeout parameter and cleanup of flags

## Solution

Adds `getFlags`function (to isolate how flags are assembled), and timeout parameter.

The rest of the non-implemented parameters are not in the stock cli and possibly should be removed from the .d.ts file.

Also got around to documenting the flags in the README :).

### CODE REVIEW

**Comment by ludicast** [comment]
Also noticed the separate package.json files (with different versions) might be part of the publishing headache. M

**Comment by andreacaldera** [comment]
> Also noticed the separate package.json files (with different versions) might be part of the publishing headache. M

Publishing issues are due to the fact we haven't implemented automatic semantic versioning yet so this relies on manual changes for now. Our on internal PRs, there's a check for preventing that but this doesn't work with forks.

@ludicast do you mind bumping up the version [here](https://github.com/marksandspencer/nx-plugins/blob/main/packages/nx-playwright/package.json#L3) for now please?

**Comment by ludicast** [comment]
:+1:  @andreacaldera, bumped version in the top level and in the package itself. lack of a blessed publishing approach is always the annoying part of the `nx` world.

**Comment by andreacaldera** [comment]
> 👍 @andreacaldera, bumped version in the top level and in the package itself. lack of a blessed publishing approach is always the annoying part of the `nx` world.
> 
> It also might be possible to either remove the top-level version or force that to determine the versions throughout, but no idea what works best for ya'll.

Thanks @ludicast, do you mind bumping up the package.json version [here](https://github.com/marksandspencer/nx-plugins/blob/main/packages/nx-playwright/package.json#L3) instead please. 
I appreciate this is not great and a bit confusing, we'll try to fix it as our next priority.

**Review by aamir-mns — APPROVED** [review]

**Comment by aamir-mns** [comment]
@ludicast thanks for bumping the versions. We have ticket to fix the versioning but for now changes in your PR looks good.

**Pull request merged**
