### PR TITLE
Fix executor not specifying a package runner

### LINKED ISSUE #78: PR #77 breaks executor
Following #77 the playwright executor no longer works.
```
PS C:\Users\.......\playwright-playground> nx e2e next-js-app-e2e --grep debugging

> nx run next-js-app-e2e:e2e --grep debugging

info  - automatically enabled Fast Refresh for 1 custom loader
event - compiled client and server successfully in 17.3s (152 modules)
[ ready ] on http://localhost:4200

 >  NX   Command failed: playwright test src --config apps/next-js-app-e2e/playwright.config.ts --grep=debugging

   'playwright' is not recognized as an internal or external command,
   operable program or batch file.
```
I believe this is because no package manager is specified in the run command within the executor:
```const command = ['playwright', 'test', path, `--config ${options.e2eFolder}/${config}`]```

### PR DESCRIPTION
**Pull request by Danphillipz**
## Problem

<sup>Fix #78 </sup>

## Solution

<sup>Specified package runner in run command</sup>

### CODE REVIEW

**Comment by andreacaldera** [comment]
> Hi @andreacaldera have put in a fix for #78 following the #77 PR :) Great work by the way on that, can now see all playwright output in a neat format (with this #79 fix) + it's all logged live which is much nicer!

@Danphillipz that change was intentional, we were planning to remove package runner. I tested it on yarn and pnpm locally before merging and it seems fine. 
Let me have a quick look and if I can't figure out the problem, we'll merge this in temporarily

**Comment by andreacaldera** [comment]
> > Hi @andreacaldera have put in a fix for #78 following the #77 PR :) Great work by the way on that, can now see all playwright output in a neat format (with this #79 fix) + it's all logged live which is much nicer!
> 
> @Danphillipz that change was intentional, we were planning to remove package runner. I tested it on yarn and pnpm locally before merging and it seems fine. Let me have a quick look and if I can't figure out the problem, we'll merge this in temporarily

It looks like running with a package manager (e.g. `yarn nx run test-app-e2e:e2e`) works correctly but running nx directly (e.g. `nx run test-app-e2e:e2e`) throws the error you reported. We could put the package manager back as optional so that people don't have to use it unless they run nx directly

**Comment by andreacaldera** [comment]
Thanks @Danphillipz, I appreciate the quick fix!
I've made a similar change in here https://github.com/marksandspencer/nx-plugins/pull/80 to re-add package manager as an optional param

**Comment by Danphillipz** [comment]
> Thanks @Danphillipz, I appreciate the quick fix! I've made a similar change in here #80 to re-add package manager as an optional param

Thanks @andreacaldera - I shall revisit this on Monday!

**Comment by Danphillipz** [comment]
Thanks @andreacaldera, V0.2.1 seems to be working great! Thanks for all the effort in the executor rewrite, this is a much improved approach!

**Pull request closed without merging**
